[tool.poetry]
name = "pyetbd"
version = "0.2.2"
description = "McDowell's (2004) ETBD implemented in Python."
authors = ["ryhigg <ryanhigginbotham@ufl.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
numba = ">=0.65.1"
numpy = ">=2.4.6"
pandas = ">=3.0.3"
openpyxl = ">=3.1.5"
memory-profiler = "^0.61.0"


[tool.poetry.group.dev.dependencies]
matplotlib = "^3.8.2"
scipy = "^1.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
