DEFAULTS = {
    "reps": 1,
    "gens": 20500,
    "experiment_type": "concurrent",
    "pop_size": 100,
    "mut_rate": 0.1,
    "low_pheno": 0,
    "high_pheno": 1023,
    "fdf_type": "linear",
    "fitness_landscape": "circular",
    "recombination_method": "bitwise",
    "fdf_mean": 40,
    "left_sched_fdf_mean": 40,
    "right_sched_fdf_mean": 40,
    "reinitialize_population": True,
    "left_sched_response_class_lower_bound": 471,
    "left_sched_response_class_upper_bound": 511,
    "right_sched_response_class_lower_bound": 512,
    "right_sched_response_class_upper_bound": 552,
    "left_sched_type": "random",
    "right_sched_type": "random",
    "schedule_type": "random",
    "interval": 20,
    "response_class_size": 41,
    "response_class_lower_bound": 471,
    "response_class_upper_bound": 512,
}
