DEFAULTS = {
    "reps": 1,
    "gens": 20500,
    "pop_size": 100,
    "mut_rate": 0.1,
    "low_pheno": 0,
    "high_pheno": 1023,
    "fdf_type": "linear",
    "fitness_landscape": "circular",
    "recombination_method": "bitwise",
    "fdf_mean": 40,
    "reinitialize_population": True,
    "schedule_type": "random",
    "schedule_subtype": "interval",
    "mean": 20,
    "response_class_size": 41,
    "response_class_lower_bound": 471,
    "response_class_upper_bound": 512,
    "excluded_lower_bound": 0,
    "excluded_upper_bound": 0,
}
